scrape_configs:
  - job_name: prometheus
    scrape_interval: 30s
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: node-exporter
    scrape_interval: 30s
    static_configs:
    - targets: ["0:9100", "0:9100", "0:9100"]

  - job_name: cadvisor
    scrape_interval: 30s
    static_configs:
    - targets: ["0:9101", "0:9101"]

